---
# tasks file for 02-k8s-prep
- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Initialize mac-list
  set_fact:
    mac_list: []
  delegate_to: localhost

- name: Get the MAC address
  set_fact: 
    mac_list: "{{ mac_list + hostvars[item]['ansible_interfaces'] | difference(['lo']) | map('regex_replace', '^(.*)$', 'ansible_\\1' ) | map('extract', hostvars[item], 'macaddress') }}"
  loop:
    "{{ ansible_play_hosts_all }}"
  run_once: yes
  delegate_to: localhost

- name: Print mac_list
  fail: 
    msg: "Macaddresses on k8s hosts not unique"
  when:
    mac_list | length != mac_list | unique | length
  delegate_to: localhost
  run_once: yes

- name: Make sure br_netfilter module is loaded
  modprobe:
    name: br_netfilter
    state: present

- name: Add br_netfilter to k8s.conf file
  copy: 
    dest: "/etc/modules-load.d/k8s.conf"
    content: |
      br_netfilter

- name: Ensure iptables correctly see bridged traffic
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Run sysctl system
  shell: sysctl -p --system
  become: yes